### ISSUE TITLE
As a user, I want to be able to walk over enemies when they have fallen.

### ISSUE THREAD

**Issue by shantahuja** [tcape/stc_game#104]
as a user, I don't want to walk around dead enemies but rather walk over them.

acceptance criteria
---------------------------
contains:
 - ability for hero character walks over dead enemies

does not contain:
 - effect for hero character to walk around dead enemies
 - any animation when hero character walks over dead enemies

**Comment by tcape** [comment]
This does it.
 public void Die(StateController controller)
    {
        controller.animator.SetBool("Dead", true);
        controller.gameObject.layer = 2;
        controller.navMeshAgent.enabled = false;
        controller.GetComponent<Rigidbody>().isKinematic = true;
        controller.GetComponent<CapsuleCollider>().enabled = false;
    }

**Comment by tcape** [comment]
![walkoverdead.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bc117ca141e620011a25d89/125516c66e82c728ace21e0d46ff9596288d95ac9dedba42a01fbcd6395428792c07b7692ac7b62abb1b2a035f5d47fd485b0916fcf9887fa4e33e768a5b19f1c32f0e2a92624cf5f2d75dad0ba821824584b3b98b4fc0ee382ce4898a462c53.PNG)
