### ISSUE TITLE
As a user, I want to have more than one ability tied to my hero class (warrior for now)

### ISSUE THREAD

**Issue by tcape** [tcape/stc_game#120]
Come up with abilities that a warrior hero should have. Create scripts and scriptable objects for these abilities and ability actions.

**Comment by tcape** [comment]
Acceptance criteria:
- At least 5 unique abilities for a warrior
- Each ability has a unique hotkey
- Scripts, and scriptable objects are stored in proper folders
- Each ability play-tested

**Comment by shantahuja** [comment]
does not contain:
 - any graphic effects
 - no particle effects
