### ISSUE TITLE
As a user, I want to access my inventory window

### ISSUE THREAD

**Issue by AuraZero** [tcape/stc_game#13]
Design the HUD overlay to display character health, money, and other pertinent information.

**Comment by dixonyant** [comment]
- Make a UI Layer that is in persistent scene.
- Design layout for the following:
- Display basic health number, mana number etc. anything that applies should be displayed.
-  Display usable abilities
- Display inventory / equipment
- Objects on the HUD that can be fully implemented later.
- Field in center screen that can be inhabited by a message box.

**Comment by shantahuja** [comment]
this window UI design may be able to be resolved by buying assets from Unity store.
https://assetstore.unity.com/packages/2d/gui/rpg-mmo-ui-3-for-ugui-32207
scroll down and check out other "EVIL" mmo GUIs
search "GUI mmo" to find more

**Comment by tcape** [comment]
This issue was started as inventory but seems to have mutated into HUD.
