### ISSUE TITLE
As a user, I want to be able to play in a dungeon

### ISSUE THREAD

**Issue by tcape** [tcape/stc_game#40]
Build a basic dungeon scene. Rooms, hallways, basic enemy placement. Navigation, lighting, decoration.
 - travel around dungeon

acceptance critera
---------------------------
contains:
 - fully created floor design
 - decorations
 - sufficient layout size that is satisfactory to the game player
 - variant lighting
 - waypoint to town
 - graphically static scene (no mobs or interactables)
 - animated static objects
 - is navigatable 

does not contain:
 - NPCs, or any interaction with NPCs
 - functionality
 - mobs, or any interaction with mobs

**Comment by shantahuja** [comment]
tim 2.5.19 - worked on dungeon_1, added sets of patrol mobs to hallways and idle mobs to rooms, started  implementing attack actions for enemies
